/**
 * PRD drift analysis — prompt construction for comparing a PRD
 * against the actual codebase analysis.
 *
 * This module handles the case where drift analysis is run as a
 * separate LLM call (e.g., when the combined prompt would exceed
 * context limits, or for higher-quality dedicated analysis).
 *
 * In the default v1 flow, drift is included in the main prompt
 * (see prompt.ts). This module is used for standalone drift analysis
 * or as a fallback when the main prompt didn't produce drift output.
 */

import type { CollectedFile } from "./collect";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface DriftPromptInput {
  projectName: string;
  /** The raw PRD content provided by the user. */
  prdContent: string;
  /** The already-generated AS_BUILT_AGENT.md (the codebase analysis). */
  agentMd: string;
  /** Optional: directory tree for additional context. */
  tree?: string[];
}

// ─── Prompt template ─────────────────────────────────────────────────────────

const DRIFT_SYSTEM = `You are as_built's drift analysis engine. Your purpose is to perform a rigorous, forensic comparison between a Product Requirements Document (PRD) and an actual codebase analysis to identify where reality diverges from the plan.

Core principles:
- **Factual and evidence-based.** Every claim must reference a specific PRD section number AND a specific code file or module. No unsupported assertions.
- **Neutral tone.** You document divergences, not judge them. "The PRD specified X but Y was built" is correct. "The developer made a mistake" is not.
- **Complete coverage.** Every feature, requirement, and specification in the PRD must be accounted for — either as implemented, partially implemented, missing, or modified.
- **Uncertainty is acceptable.** When you cannot determine implementation status, mark it "[NEEDS VERIFICATION]" and explain what evidence you looked for but could not find.
- **Both directions matter.** Drift can mean "PRD says X but code does Y" AND "code does Z but PRD never mentioned it." Capture both.`;

const DRIFT_INSTRUCTIONS = `## Drift Analysis Instructions

Systematically compare every requirement in the PRD against the codebase analysis (AS_BUILT_AGENT.md). Produce a structured PRD_DRIFT.md report.

### Analysis Methodology

1. **Extract all requirements from the PRD.** Read through the PRD section by section. For each section, identify every discrete requirement, feature, or specification. A single PRD section may contain multiple requirements.

2. **Search the codebase analysis for evidence.** For each requirement, look for:
   - Direct implementation (function, module, endpoint, config that fulfills the requirement).
   - Partial implementation (some aspects are built but not all).
   - Stubs or TODOs that reference the requirement.
   - Complete absence of any related code.

3. **Check for scope additions.** Read through the codebase analysis and identify any features, modules, or capabilities that have no corresponding PRD section.

4. **Assess architectural alignment.** Compare technical decisions (tech stack, patterns, data model) between PRD and implementation.

### Document Structure

Begin with:
\`\`\`
# PRD_DRIFT.md — {projectName}
> Generated by as_built | {date}
> Comparison of PRD specification vs. actual implementation.
\`\`\`

Then produce these sections IN ORDER:

### 1. Summary
3-5 sentences capturing the headline story:
- Approximate implementation coverage (what percentage of PRD features have corresponding code).
- The most significant area of alignment (what was built most faithfully).
- The most significant area of drift (where reality diverges most from plan).
- Overall trajectory: is the project on track, ahead, or behind the PRD?

### 2. Fully Implemented
Features from the PRD that are **complete and match the specification**. Use a table:

| PRD Section | Requirement | Implementation Evidence |
|-------------|------------|----------------------|
| §8.1 | Zip upload with 100MB limit | \`lib/input/zip-handler.ts\`, \`app/api/scan/route.ts\` (size validation) |

Keep rows concise. The goal is confirmation, not re-documentation.

### 3. Partially Implemented / Modified
Features that **exist but differ from the PRD**. For each:

**Feature: [Name] (PRD §X.Y)**
- **PRD specified:** [Direct quote or close paraphrase of the requirement]
- **Actual implementation:** [What the code does, with file references]
- **Nature of deviation:** [Simplified | Expanded | Different approach | Deferred partially | Reordered]
- **Impact:** [Low — cosmetic/naming difference | Medium — behavioral difference | High — core behavior changed]
- **Notes:** [Any context, e.g., "TODO comment in file suggests this is planned for v2"]

### 4. Missing / Not Started
Features in the PRD with **no corresponding code**. For each:

**Feature: [Name] (PRD §X.Y)**
- **PRD specified:** [What was required]
- **Code evidence:** [None found | Stub at \`path/file.ts:line\` | TODO comment at \`path/file.ts:line\`]
- **Assessment:** [Not started | Intentionally deferred (cite evidence) | Possibly implemented under different name (explain)]

### 5. Scope Additions
Features in the code with **no PRD counterpart**. For each:
- **What:** Description of the feature or module.
- **Where:** File paths that implement it.
- **Likely reason:** Infrastructure necessity | Developer tooling | Discovered requirement during build | Dependency of a PRD feature | Unknown

### 6. Architectural Divergences
Technical decisions that differ from the PRD specification:

| PRD Decision (§) | PRD Specified | Actually Built | Assessment |
|-------------------|--------------|---------------|------------|
| §5 Database | PostgreSQL | Firestore | Trade-off: simpler setup, lost relational queries |

For each divergence, note whether it appears to be an improvement, a trade-off, or a potential concern — but present this as analysis, not judgment.

### 7. Alignment Score

| Metric | Value |
|--------|-------|
| **Overall Score** | High (>80%) / Medium (50-80%) / Low (<50%) |
| **Features Implemented** | X of Y PRD requirements have corresponding code |
| **Implementation Fidelity** | Of implemented features: X match spec exactly, Y are modified |
| **Scope Additions** | Z features exist that were not in PRD |
| **Recommendation** | [Update PRD to match reality / Implementation needs alignment / PRD is current] |

Close with 2-3 sentences of narrative summary explaining the score.`;

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Builds a standalone drift analysis prompt from a PRD and an
 * already-generated codebase analysis.
 *
 * Use this when:
 * - The combined prompt (analysis + drift) exceeds context limits.
 * - The main scan didn't produce a drift section and you need a retry.
 * - You want higher-quality drift analysis via a dedicated call.
 */
export function buildDriftPrompt(input: DriftPromptInput): string {
  const { projectName, prdContent, agentMd, tree } = input;
  const date = new Date().toISOString().split("T")[0];

  const instructions = DRIFT_INSTRUCTIONS.replace(
    "{projectName}",
    projectName,
  ).replace("{date}", date);

  const sections: string[] = [
    DRIFT_SYSTEM,
    "",
    `# Project: ${projectName}`,
    `# Date: ${date}`,
    "",
    instructions,
  ];

  // Add directory tree if available
  if (tree && tree.length > 0) {
    sections.push(
      "",
      "## Project Directory Structure",
      "",
      "```",
      tree.join("\n"),
      "```",
    );
  }

  // Add PRD content
  sections.push(
    "",
    "## Original PRD Document",
    "",
    "Read this document section by section. Extract every discrete requirement, feature, and specification.",
    "",
    "===BEGIN_PRD===",
    prdContent,
    "===END_PRD===",
  );

  // Add codebase analysis
  sections.push(
    "",
    "## Codebase Analysis (AS_BUILT_AGENT.md)",
    "",
    "This is the ground truth of what was actually built. Search this document for evidence of each PRD requirement.",
    "",
    "===BEGIN_ANALYSIS===",
    agentMd,
    "===END_ANALYSIS===",
  );

  // Final instruction
  sections.push(
    "",
    "## Final Instruction",
    "",
    "Now produce the complete PRD_DRIFT.md document following the structure defined above. Account for EVERY section and requirement in the PRD. Output ONLY the PRD_DRIFT.md document — no preamble, no commentary.",
  );

  return sections.join("\n");
}
